spring:
  application:
    name: moon-service-prod
server:
  port: 1776

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}:prod
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/